### ISSUE TITLE
Mandatory relation between ThermalZone and ThermalBoundary?

### ISSUE THREAD

**Issue by oliviertournaire** [cstb/citygml-energy#118]
I am wondering if the _boundedBy_ relation between `ThermalZone` and `ThermalBoundary` is really mandatory. The cardinality is set to `1..*`.

However, if one just want to model a building and attached the properties `isCooled` or `isHeated`, he has to define a `ThermalZone`. Sounds good. However, as long as you define a `ThermalZone`, you are obliged to also model a `ThermalBoundary`. I do not think this is really necessary.

Your opinions?

**Comment by JoachimBenner** [comment]
The **mandatory** relation _boundedBy_ from _ThermalZone_ to _ThermalBoundary_ is not new, it was included in all previous versions of the Energy ADE. I think, for a real simulation it does not make sense to model a _ThermalZone_ without one or more _ThermalBoundary_.  You are right that for the simple case we only want to express that a building is heated and/or cooled, the actual model is a little bit to complex, because we need a _ThermalZone_ object and a (dummy) _ThermalBoundary_ object. But, instead of defining _boundedBy_ as optional, I would propose to define _isHeated_ and _isCooled_ also as ADE-attributes of _AbstractBuilding_.

I propose to keep the mandatory relation for 0.7.0 and postpone the problem for version 0.8.0

**Comment by oliviertournaire** [comment]
OK, agree with the proposal of having attributes _isHeated_ and _isCooled_ at in the ADE extended _AbstractBuilding_ class.

**Comment by RomainNouvel** [comment]
I understand your issue, but this will lead to a redundancy/conflict if a AbstractBuilding with attribute isHeated has ThermalZone without this attribute (or isHeated = false). In the guidelines, we've defined the ThermalZone as "the volume unit for heat/cool energy demand calculation.". Then, we won't need the information if an AbstractBuilding is heated or not if a ThermalZone is not defined.

For some statistical models, we might use the ThermalZone without ThermalBoundaries. Then, I would rather propose to set the cardinality of boundedBy relation to (0..*) instead of (1..*). Do you agree?

**Comment by gioagu** [comment]
It seems reasonable to me, so I agree - unless we come up with some bigger issues

**Comment by JoachimBenner** [comment]
Making the relation boundedBy optional surely causes no problems. In any case, I think that attributes "isHeated" and "isCooled" make sense on the general CityGML level, but to regard this level is not the job of this working group.

**Comment by JoachimBenner** [comment]
Can we agree on this change for version 0.9.0:

The relation _boundedBy_ (_ThermalZone_ --> _ThermalBoundary_) has cardinality **0..***

**Comment by RomainNouvel** [comment]
I vote for it.

**Comment by eRolland** [comment]
I vote for it too.

**Comment by gioagu** [comment]
OK for me
