### ISSUE TITLE
Emitters

### ISSUE THREAD

**Issue by RomainNouvel** [cstb/citygml-energy#129]
Emitters (also called end use unit or zoning system) have been modelled in an earlier version of the Energy ADE (0.4.3) before to be removed for simplification purpose.
They mainly relate to the end use types SpaceHeating, SpaceCooling and Ventilation.
It could be interested to integrate them again in the schema, either directly connected to the EnergyDemand object or as attribute of the DistributionSystem.
Emitters could be an object with as attributes: emitter type (radiators ect.), heatExchangeType, installed power, number etc...

**Comment by mlauster** [comment]
Sound like a good idea, they are technically the missing link between energy conversion and energy use. Currently, I would vote for connected to distribution system, but I'm open for other opinions.

**Comment by kwakuwulf** [comment]
I agree. We were discussing the same issue today internally. Emitter types in industry could be heat exchanger, direct infusion of steam, jacketed vessel, ...

**Comment by RomainNouvel** [comment]
Request of Change:

- introduction of a new object "Emitter", with a relation 0..* from EnergyDistributionSystem to Emitter
- Emitter has the following attributes : emitterType(0.1) [Enumeration] , installedPower(0.1) [MeasuredType], unitNumber(0.1) [Integer], thermalExchange(0,1) [heatExchangeType].
- the values of the emitterTypeEnumeration are : radiators, convectors, radiant floor, radiant ceiling, radiant wall, split-unit, 2-pipes fan coil unit, 4-pipes fan coil unit

**Comment by mlauster** [comment]
@RomainNouvel, we had the the question how to model heat recovery from `Emitter` related processes. E.g. the emitter is an oven, how to model that a part of the heat can be reused, e.g. at the back of the oven. If we define the oven as an `EnergyConversionSystem`, we could use the relation to `FinalEnergy` to model that. So the question is, should we add the same relation as for `EnergyConversionSystem` to `Emitter` so that `Emitter`can produce and consume `FinalEnergy`? Quite complex question, from a technical point `EnergyConversionSystems`and `Emitters`are very similar, both convert energy, either by its form or by its temperature.

**Comment by mlauster** [comment]
And what about electrical emitter? Should we add the same structure as for 'ThermalDistributionSystem`and `PowerDistributionSystem` and add `Emitter` as well to the electrical part, e.g. a lighting system?

**Comment by JoachimBenner** [comment]
I propose to close this issue and continue the discussion under issue #137

**Comment by RomainNouvel** [comment]
ok
