### ISSUE TITLE
EnergyConversionSystem as abstract class

### ISSUE THREAD

**Issue by JoachimBenner** [cstb/citygml-energy#144]
In the actual version, we declared __EnergyDistributionSystem_ and __StorageSystem_ as **abstract** classes, because we want to ensure that only the specializations like _ThermalDistributionSystem_ are instanziated in an EnergyADE document. Is there a reason why we treat _**EnergyConversionSystem**_ in a different manner? There are many specific classes for energy conversion systems being derived from the base class _EnergyConversionSystem_, but it is still possible to use the base class.

**Comment by RomainNouvel** [comment]
Few years ago, we agreed that it would be possible to use a generic EnergyConversionSystem with few details like efficiency, operating mode etc. This can be useful in the cases where:
- we don't know exactly the type of system
- this is a new/hybrid system

**Comment by gioagu** [comment]
In order to accomodate this need, and also in order to have a sort of design "coherency" with the other _EnergySystems, what about keeping the _EnergyConversionSystem also abstract, but to add a "GenericConversionSystem" class, with no other attributes than those inherited from the abstract class?
This is also the way it is done in the UtilityNetwork ADE when they need to deal with a "generic" object.
