### ISSUE TITLE
move guidelines to doc

### ISSUE THREAD

**Issue by mlauster** [cstb/citygml-energy#71]
Would it make sense to move guidelines to doc?

**Comment by oliviertournaire** [comment]
OK, made it by commit https://github.com/cstb/citygml-energy/commit/c587efc71089cfc6826889e1b51788f5bd86d796.

@mlauster can you please create the following structure, as suggested by @RomainNouvel: create in `doc/guidelines` a `doc/guidelines/pdf_generator` directory so that only remains in `doc/guidelines` the `.md` and `.pdf` files.

**Comment by mlauster** [comment]
@emunozh, that sounds more like something for you. In addition, we have no current pdf-version of our guidelines, what leads to a broken link in Readme.

**Comment by emunozh** [comment]
please see #80. I will commit some more changes this week, the pdf file is still missing because the document compilation happens now under folder `build/`.
