### ISSUE TITLE
About attribute "atticType" in building

### ISSUE THREAD

**Issue by gioagu** [cstb/citygml-energy#74]
Some comments for the next 0.7 version collected so far.

Giorgio: The attribute atticType (and the similar ones) could be renamed “atticConditioning”, as we describe just one property of the attic, not really the “type”. But it is just a just thought

Romain: Should be discussed. We should look for the official name in the ISO 13790 and similar norms… -> Issue for Energy ADE 0.7? 

Joachim: Should be a topic for Energy ADE version 0.7

**Comment by JoachimBenner** [comment]
I wonder whether the Enumeration **ConditioningType** is sufficient. The term "Conditioned" means "_either heated or collod or both_", but we cannot precisely specify the case where attic/basement is only heated, but not cooled. 
Proposal: ConditioningType: *HeatedAndCooled, Heated, Cooled, Unconditioned, None*.

I would stick to the property names "atticType" and "basementType", because the Enumeration also covers the the case that no attic or basement exist.

**Comment by RomainNouvel** [comment]
well... this is not only about "heated" or "cooled" but rather if attic and Basement are inside the thermal building envelope (directly or undirectly heated/cooled), or outside (separated from it with an insulation), and, consequently, if its floorArea Count in the building floor area and nettoVolume.

If "conditioned" is not satisfying, what about "inhabited", "uninhabited", "None"? Is there not a reference codeList already existing (e.g. in the INSPIRE database)?

PS:
If we have detailled Information about the usage and hvac systems of the attic and Basement, then we can model them like a single ThermalZone (with attributes isHeated and isCooled).

**Comment by JoachimBenner** [comment]
"includedIedInThermalHull", "notIncludedInThermalHull", "notExisting" ???
Must be discussed further

**Comment by RomainNouvel** [comment]
other value Propositions:
1- "insideBuildingThermalBoundary", "outsideBuidingThermalBoundary", "notExisting" (the definition are straight forward)
2- "partOfBuildingUsedArea", "notBuildingUsedArea", "notExisting" (rather focused on the calculation of the floor area)

**Comment by JoachimBenner** [comment]
Can we agree on Romain's proposal 1?

**Comment by RomainNouvel** [comment]
The type name "ConditioningType" is obsolete now. Which other type name can we use?

**Comment by RomainNouvel** [comment]
Discussion during Workshop Vienna:
- Marc: are the atticType and basementType really required in the model? (possibility to model directly ThermalZone and UsageZone related to it. To specific on residential buildings, what about garage etc...)
- Piergiorgio: we can use HeightAboveGround Type like in INSPIRE -> http://inspire.ec.europa.eu/documents/Data_Specifications/INSPIRE_DataSpecification_BU_v3.0.pdf (p30)

**Comment by RomainNouvel** [comment]
Following our discussion with Marc and Piergiorgio during the meeting, here is a proposed request of change:
- Delete parameter atticType and basementType of _AbstractBuilding (too specific to a type of residential buildings)
- Add object (datatype) HeightAboveGround, whose 2 mandatory attributes are value (LengthType) and HeightReference (type enumeration ElevationReferenceValue = {bottom of construction, entrance 
point, general eave, general ground, general roof, general roof edge, highest eave, highest ground point, highest point, highest roof edge, lowest eave, lowest floor above ground, lowest ground point, lowest roof edge, top of construction} as in INSPIRE)
- Add parameter heightAboveGround in _AbstractBuilding. Cardinaty [0..*], type HeightAboveGround.
- Delete parameters basementCeilingHeightAboveGround, eavesHeight and ridgeHeight of _AbstractBuilding

**Comment by JoachimBenner** [comment]
I agree to introduce a more flexible data structure for the building height instaed of the special properties "basementCeilingHeight", "ridgeHeighjt", ... However, why not using the full INSPIRE data type "HeightAboveGround", which has 4 attributes. As minimum, a "heightReference" is needed for the lower and the upper height reference.

I do not understand how to retrieve the atticType or basemantType from building height values, @RomainNouvel could you explain this?

**Comment by RomainNouvel** [comment]
- The full INSPIRE data type is indeed very flexible, with the 2 attributes heightReference and lowReference, which can both be any ElevationReferenceValue. However, from the software development point of view, this extrem flexibility with 9*9=81 possible combinations is very difficult to handle. In the Energy ADE, we could fix for instance generalGround as lowReference, having only 9 possibly defined heightAboveGround.

- Concerning the atticType, we should introduce a new ElevationReferenceValue = topCeiling (or more explicit : topThermalBoundary), corresponding to the ceiling of the highest conditioned area of a building. Then we would be able to define the upper thermal boundary conditions much more precisely than with the atticType.
- for the basementType, bottom of construction and lowestFloorAboveGround would allow us to define a possible basement or inform us that there is no basement. To know if the basement is heated or not, we could introduce a new ElevationReferenceValue = bottomThermalBoundary. Then we would be able to define the bottom thermal boundary conditions much more precisely than with the basement Type.

**Comment by JoachimBenner** [comment]
This concept surely is very flexible, but also quite difficult to understand and use. We need a number of specific height values only to distinguish between two situations: "There is no basement / attic", or "there is a basement / attic which is not within the thermal hull". If basement / attic would belong to the thermal hull, they must be modelled as separate ThermalZone objects.

I wonder whether the destinction cannot be expressed by the **thermalBoundaryType of the lowest / highest ThermalZone**. 

For the lowest ThermalZone: 

- If the building has no basement, the thermalBoundaryType of the "floor" of this zone could be "GroundSlab" (must be added to the enumeration instead of BasementFloor). 
- If the building has a basement outside the thermal hull, the thermalBoundaryType is "BasementCeiling"
- If the building has a basement inside the thermal hull, the thermalBoundaryType is "IntermediaryFloor"

For the highest ThermalZone:

- If the building has no attic, the thermalBoundaryType of the "ceiling" of this zone is "Roof"
- If the building has an attic outside the thermal hull, the thermalBoundaryType is "AtticFloor"
-  If the building has an attic inside the thermal hull, the thermalBoundaryType is "IntermediaryFloor"

**Comment by RomainNouvel** [comment]
Very good idea Joachim. Then we should add "AtticFloor" and "GroundSlab" in our enumeration "ThermalBoundaryType". The HeightAboveGround would then complement this ThermalBoundaryType information by giving the position of these thermal boundaries.

**Comment by JoachimBenner** [comment]
Done

**Comment by oliviertournaire** [comment]
@RomainNouvel @JoachimBenner Currently, the _HeightAboveGround_ dataType has been added, and also the _ElevationReferenceValue_ enumeration. However, the enumeration does not contain the values proposed by Romain _highestGroundPoint_ and _lowestGroundPoint_. Is it intended?

All other proposals have been implemented

**Comment by JoachimBenner** [comment]
Yes. All height values are measured relative to _"generalGroundPoint"_. Thus, _highestGroundPoint_ and _lowestGroundPoint_ would deliver hight information on the relief surrounding the building, but no building hight.

**Comment by oliviertournaire** [comment]
OK, so lets close the issue!
